### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by mxtilx** [liujiaqi7998/EasyGrasscutters#1]
无法访问此网站网址为 wss://43.248.***.***:1514/easy/H**** 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by liujiaqi7998** [comment]
wss://43.248..:1514/easy/H****这个地址不是用来直接访问的，如果你仔细阅读说明https://flows.nodered.org/node/node-red-easy-grasscutters    会发现，这个地址是输入在连接框里的
