### ISSUE TITLE
node-red启动问题

### ISSUE THREAD

**Issue by mxtilx** [liujiaqi7998/EasyGrasscutters#11]
npm install -g --unsafe-perm node-red
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.

changed 292 packages, and audited 293 packages in 36s

39 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 low, 1 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\Administrator> node-red:
node-red: : 无法将“node-red:”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼
写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ node-red:
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (node-red::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Administrator> node node_modules/node-red/red.js
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\node_modules\node-red\red.js'
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m
[90m    at node:internal/main/run_main_module:23:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

Node.js v18.12.1
PS C:\Users\Administrator>

**Comment by liujiaqi7998** [comment]
请查阅node-red相关资料，与本项目无关
