### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by mxtilx** [liujiaqi7998/EasyGrasscutters#2]
首次进入的玩家，以玩家身份执行命令
这个该如何操作

**Comment by liujiaqi7998** [comment]
像这个样子
![image](https://user-images.githubusercontent.com/34202289/188259766-5cbacd66-d3ae-4443-80c0-087e0c5172b1.png)
![image](https://user-images.githubusercontent.com/34202289/188259812-976d91f9-3980-4f00-88af-1bd43ae53b67.png)

**Comment by liujiaqi7998** [comment]
下面是例程，直接复制导入即可：
[
    {
        "id": "74ff4514e6ee0e7f",
        "type": "tab",
        "label": "流程 2",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "4e2769aa6fe5e18b",
        "type": "switch",
        "z": "74ff4514e6ee0e7f",
        "name": "是否是第一次进入",
        "property": "payload.is_first",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "true",
                "vt": "jsonata"
            },
            {
                "t": "eq",
                "v": "false",
                "vt": "jsonata"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 390,
        "y": 140,
        "wires": [
            [
                "24c8c03bb94c3dff"
            ],
            [
                "7efa232ef0c50162"
            ]
        ]
    },
    {
        "id": "24c8c03bb94c3dff",
        "type": "debug",
        "z": "74ff4514e6ee0e7f",
        "name": "debug 22",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 620,
        "y": 120,
        "wires": []
    },
    {
        "id": "7efa232ef0c50162",
        "type": "debug",
        "z": "74ff4514e6ee0e7f",
        "name": "debug 23",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 620,
        "y": 220,
        "wires": []
    },
    {
        "id": "bc7daf1b888c4e61",
        "type": "OnPlayerJoin",
        "z": "74ff4514e6ee0e7f",
        "server": "e1d3427ee4fffb1b",
        "x": 170,
        "y": 140,
        "wires": [
            [
                "4e2769aa6fe5e18b"
            ]
        ]
    },
    {
        "id": "e6c8b3372326ac3b",
        "type": "comment",
        "z": "74ff4514e6ee0e7f",
        "name": "true 是第一次进入",
        "info": "",
        "x": 830,
        "y": 120,
        "wires": []
    },
    {
        "id": "94ff40aa0aea1e23",
        "type": "comment",
        "z": "74ff4514e6ee0e7f",
        "name": "false 不是第一次进入",
        "info": "",
        "x": 840,
        "y": 220,
        "wires": []
    },
    {
        "id": "e1d3427ee4fffb1b",
        "type": "remote-server",
        "url": "wss://aaaaa/easy/jW6wEeBN",
        "No_certificate": false
    }
]
