### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by mxtilx** [liujiaqi7998/EasyGrasscutters#3]
这二个怎么连接
![Screenshot_2022-09-03-15-35-23-11](https://user-images.githubusercontent.com/96869052/188261179-575c2c7b-6d5a-499c-9b1f-d0805985f718.jpg)

**Comment by liujiaqi7998** [comment]
首未连接，将“以玩家身份执行命令”里面的内容转移到“玩家UID里面”，然后去掉”里面的内容转移到“在顺次连接，建议学习一下NodeRed
