### ISSUE TITLE
[bug?] 

### ISSUE THREAD

**Issue by ERthereal** [liujiaqi7998/EasyGrasscutters#4]
我想知道怎么解决
4 Sep 06:35:45 - [warn] [remote-server:d335d3f77a48a3e8] [EasyGrasscutters] 连接错误：self-signed certificate
4 Sep 06:35:45 - [warn] [remote-server:d335d3f77a48a3e8] [EasyGrasscutters] 连接断开：undefined

**Comment by liujiaqi7998** [comment]
证书问题，勾选跳过SSL检测
