### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Rainbow-rose** [liujiaqi7998/EasyGrasscutters#6]
刚接触node-red，使用例程部署的时候显示 工作区包含一些未正确配置的节点 ，忽略之后成功部署，游戏中无任何变化，请问需要如何处理

**Comment by longhuan1999** [comment]
inject节点开始的流程，需要手动点一下
![image](https://user-images.githubusercontent.com/43313501/189515539-a32a5075-c2f1-4ef5-b97d-04acbc0fccfc.png)
![image](https://user-images.githubusercontent.com/43313501/189515604-e6dde1f0-db13-49bc-bcbf-3450b660e6ca.png)

**Comment by liujiaqi7998** [comment]
感谢@longhuan1999 的配图回复
是的，首先你需要检查是否连接正常，连接正常的情况下，就是需要点击触发一下

**Comment by Rainbow-rose** [comment]
谢谢大佬们解答
