### ISSUE TITLE
我是一个小白，我只想要原剧情，有没有大佬教一下

### ISSUE THREAD

**Issue by CM671** [liujiaqi7998/EasyGrasscutters#7]
node-red安装好了，弄好插件部署完下一步是什么，到目前为止一点变化也没有。。。

**Comment by liujiaqi7998** [comment]
没有实现完整剧情的方法，需要你自己手动去创建。

**Comment by longhuan1999** [comment]
你可能需要先学习一下NodeRed。
顺便提一下我偶然发现的Grasscutter分支，https://github.com/Hartie95/Grasscutter/tree/quests 修复了许多原剧情触发器（需配合Grasscutter开启大世界脚本），大大简化了原剧情流程设计的难度和复杂度
